{
  "throws": "Await cannot be used as name inside an async function (1:20)"
}